# RocketMQ Broker 配置（dev 环境单机）
brokerClusterName=DefaultCluster
brokerName=broker-a
brokerId=0
# 指向 NameServer（docker 网络内用服务名）
namesrvAddr=rocketmq-namesrv:9876
# 主机可访问的 broker 地址（端口 10911 已映射到宿主 127.0.0.1）
brokerIP1=127.0.0.1
deleteWhen=04
fileReservedTime=48
brokerRole=ASYNC_MASTER
flushDiskType=ASYNC_FLUSH
# 允许自动创建主题（dev 便捷，生产应预建）
autoCreateTopicEnable=true
autoCreateSubscriptionGroup=true
# 存储路径（挂载卷）
storePathRootDir=/home/rocketmq/store
storePathCommitLog=/home/rocketmq/store/commitlog
